CREATE TABLE IF NOT EXISTS mpa_rate (
        mpa_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name varchar(40)
);
CREATE TABLE IF NOT EXISTS film (
        film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(40) NOT NULL,
        description varchar(200) NOT NULL,
        release_date date,
        duration INTEGER,
		rate INTEGER,
        mpa_rate_id INTEGER REFERENCES mpa_rate (mpa_rate_id)
); 
CREATE TABLE IF NOT EXISTS genre (
        genre_id INTEGER PRIMARY KEY,
		name varchar(40)
);
CREATE TABLE IF NOT EXISTS film_genre (
		film_id INTEGER REFERENCES film (film_id),
        genre_id INTEGER REFERENCES genre (genre_id),
		CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id)
); 
CREATE TABLE IF NOT EXISTS users (
        users_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar(40) NOT NULL,
        login varchar(40) NOT NULL,
		name varchar(40) NOT NULL,
        birthday date
); 
CREATE TABLE IF NOT EXISTS film_likes (
        film_id INTEGER REFERENCES film (film_id),
        users_id INTEGER REFERENCES users (users_id),
		CONSTRAINT pk_film_likes PRIMARY KEY (film_id, users_id)
); 
CREATE TABLE IF NOT EXISTS friendship (
        user_id_1 INTEGER REFERENCES users (users_id),
        user_id_2 INTEGER REFERENCES users (users_id),
		friends BOOL,
		CONSTRAINT pk_friendship PRIMARY KEY (user_id_1, user_id_2)
); 